on:
    pull_request:
      branches: 
        - main
    workflow_dispatch:

jobs:
    store-front:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: install dependencies
              run: npm install
              working-directory: src/store-front

            - name: build the package
              run: npm run build
              working-directory: src/store-front
            - name: run test
              run: npm run
              working-directory: src/store-front
            - name: Zip build output
              run: zip -r dist.zip src/store-front/dist/
            - name: publish test results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                 files: |
                
                    **/src/store-front/dist/*.html
             
              
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: dist.zip
