on:
    pull_request:
      branches: 
        - main
    workflow_dispatch:

jobs:
    store-front:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: install dependencies
              run: npm install
              working-directory: src/store-front

            - name: build the package
              run: npm run build
              working-directory: src/store-front

            - name: Zip build output
              run: zip -r dist.zip src/store-front/dist/
            
            - name: Run tests
              run: npm test -- --ci --reporters=jest-junit
              working-directory: src/store-front

            - name: Publish test results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()   # ensure results are published even if tests fail
              with:
                files: src/store-front/junit.xml
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: dist.zip